### ISSUE TITLE
Canvas is not a constructor

### ISSUE THREAD

**Issue by SpeedoPasanen** [image-js/hog#4]
Hi,

the default export of node-canvas is no longer a constructor, thus "_environment.Canvas is not a constructor" error. This fixes it:

Change `var canvas = new _environment.Canvas(w, h);`
to: `var canvas = _environment.Canvas.createCanvas(w, h);`
in `load.js`

**Comment by targos** [comment]
Hi, thanks for the bug report!

I published version 0.1.0 of this package with the fix.
